#!/usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
The golden corpus and reference pipeline for the determinism harness.

The corpus is generated by seeded code rather than checked in as data, which keeps it out of LFS while remaining
every bit as fixed: the same seed produces the same rows forever. It covers the cases determinism control 13 names:
normal traffic across several entities and windows, a single-row entity, clock-skewed records that arrive out of
order but inside the lateness horizon, late arrivals past the horizon, an empty window between active ones, a
malformed flow row, and an address that no binding covers.

The pipeline is the full lineage chain from the OSI behavioral analytics guide: lineage stamping, Community ID,
binding resolution, and deterministic window sealing.
"""

import random
import typing

import pandas as pd

from morpheus.config import Config
from morpheus.messages import ControlMessage
from morpheus.pipeline import LinearPipeline
from morpheus.stages.input.in_memory_source_stage import InMemorySourceStage
from morpheus.stages.lineage.binding_resolver_stage import BindingResolverStage
from morpheus.stages.lineage.community_id_stage import CommunityIdStage
from morpheus.stages.lineage.lineage_stamp_stage import LineageStampStage
from morpheus.utils.column_assign import to_host
from morpheus.stages.lineage.window_seal_stage import WindowSealStage
from morpheus.stages.output.in_memory_sink_stage import InMemorySinkStage
from morpheus.utils.binding_table import NS_PER_SECOND
from morpheus.utils.binding_table import BindingTable
from morpheus.utils.determinism import canonicalize

CORPUS_SEED = 20260830

PERIOD_SECONDS = 300
LATENESS_SECONDS = 900

# The canonical row key and the columns two runs may legitimately differ in (none, for this pipeline).
KEY_COLUMNS = ["event_uid", "is_late"]
IGNORE_COLUMNS: list[str] = []

_ENTITIES = [
    ("10.0.1.10", "aa:bb:cc:00:00:10", "Gi1/0/10"),
    ("10.0.1.11", "aa:bb:cc:00:00:11", "Gi1/0/11"),
    ("10.0.1.12", "aa:bb:cc:00:00:12", "Gi1/0/12"),
]


def build_binding_table() -> BindingTable:
    """The lease table the corpus resolves against; one address is deliberately never covered."""
    hour_ns = 3600 * NS_PER_SECOND
    rows = pd.DataFrame({
        "ip": [ip for (ip, _, _) in _ENTITIES],
        "mac": [mac for (_, mac, _) in _ENTITIES],
        "port_id": [port for (_, _, port) in _ENTITIES],
        "bind_start": [0] * len(_ENTITIES),
        "bind_end": [24 * hour_ns] * len(_ENTITIES),
    })

    return BindingTable.from_dataframe(rows,
                                       name="dhcp_lease",
                                       key_column="ip",
                                       value_columns=["mac", "port_id"],
                                       start_column="bind_start",
                                       end_column="bind_end")


def build_corpus() -> pd.DataFrame:
    """
    Build the fixed input corpus, one row per network flow observation.

    Every value is derived from `CORPUS_SEED`, so the corpus is as fixed as a checked-in file while remaining
    reviewable as code.
    """
    rng = random.Random(CORPUS_SEED)
    rows = []

    def add(time_s: float, src_ip: str, collector: str, dst_ip: str = "192.0.2.50", protocol: str = "tcp"):
        rows.append({
            "event_time": int(time_s * NS_PER_SECOND),
            "src_ip": src_ip,
            "dest_ip": dst_ip,
            "protocol": protocol,
            "src_port": rng.randrange(1024, 65535),
            "dest_port": 443,
            "collector_id": collector,
            "schema_version": "TC-3/1.0.0",
            "origin_hash": f"{rng.getrandbits(64):016x}",
        })

    # Normal traffic: three entities active through windows 0, 1, and 2 ([0, 300), [300, 600), [600, 900) seconds).
    for window_start in (0, 300, 600):
        for (ip, _, _) in _ENTITIES:
            for _ in range(4):
                add(window_start + rng.uniform(1, 299), ip, "col-a")

    # Clock skew: records that arrive out of order but within the lateness horizon, so they are on time.
    add(610.0, _ENTITIES[0][0], "col-b")
    add(305.5, _ENTITIES[0][0], "col-b")
    add(12.25, _ENTITIES[1][0], "col-b")

    # A single-row entity, unknown to the binding table, so it also exercises the unresolved path.
    add(320.0, "10.0.9.99", "col-b")

    # An empty window: nothing between [900, 1200) seconds; activity resumes in window 4 and then jumps far
    # enough ahead to seal everything up to it.
    for (ip, _, _) in _ENTITIES:
        add(1210.0 + rng.uniform(0, 80), ip, "col-a")

    add(3600.0, _ENTITIES[2][0], "col-a")

    # Late arrivals: rows for window 0 and window 1 arriving after the watermark passed their horizons.
    add(15.0, _ENTITIES[0][0], "col-c")
    add(410.0, _ENTITIES[1][0], "col-c")

    # A malformed flow: the address cannot be hashed, so the Community ID is null but the row must survive.
    add(3620.0, "not-an-address", "col-c")

    df = pd.DataFrame(rows)
    df["collector_seq"] = range(1, len(df) + 1)

    return df


def build_pipeline_config(use_cpp: bool = False, execution_mode=None) -> Config:
    """
    A pipeline configuration, defaulting to CPU mode and importable without a GPU.

    Parameters
    ----------
    use_cpp : bool, default = False
        Whether stages may use their C++ implementations.
    execution_mode : `morpheus.config.ExecutionMode`, optional
        Mode to build for. Defaults to CPU. See `telemetry_pipeline.build_pipeline_config` for why the parameter
        exists: the composed pipeline is the only thing that can say whether the two modes agree, and the
        per-stage variants cannot.
    """
    # Imported here so the module can be inspected without a full Morpheus runtime.
    from morpheus.config import CppConfig
    from morpheus.config import ExecutionMode

    CppConfig.set_should_use_cpp(use_cpp)

    config = Config()
    config.execution_mode = ExecutionMode.CPU if execution_mode is None else execution_mode

    return config


DEFAULT_ORDER_COLUMNS = ["event_time", "collector_id", "collector_seq"]


def run_pipeline(config: Config,
                 dataframes: list[pd.DataFrame],
                 order_columns: typing.Optional[list[str]] = None) -> pd.DataFrame:
    """
    Run the reference lineage pipeline over the given source frames and return the canonicalized output.

    Parameters
    ----------
    config : `morpheus.config.Config`
        Pipeline configuration.
    dataframes : list of `pandas.DataFrame`
        Source frames; how the corpus is split across them is the batching under test.
    order_columns : list of str, optional
        Passed through to `WindowSealStage`. Defaults to the guide's total row order. The permutation check's
        negative control passes an explicit `[]` to reproduce the removed-sort defect and prove the harness
        catches it.

    Returns
    -------
    `pandas.DataFrame`
        The concatenated, canonicalized output of every emitted window.
    """
    if (order_columns is None):
        order_columns = DEFAULT_ORDER_COLUMNS

    pipe = LinearPipeline(config)
    pipe.set_source(InMemorySourceStage(config, dataframes=dataframes))
    pipe.add_stage(
        LineageStampStage(config, id_columns=["collector_id", "schema_version", "origin_hash", "collector_seq"]))
    pipe.add_stage(CommunityIdStage(config))
    pipe.add_stage(BindingResolverStage(config, binding_table=build_binding_table(), key_column="src_ip"))
    pipe.add_stage(
        WindowSealStage(config,
                        period_seconds=PERIOD_SECONDS,
                        lateness_seconds=LATENESS_SECONDS,
                        order_columns=order_columns if len(order_columns) > 0 else None))
    sink = pipe.add_stage(InMemorySinkStage(config))

    pipe.run()

    frames = []

    for message in sink.get_messages():
        meta = message.payload() if isinstance(message, ControlMessage) else message
        df = meta.copy_dataframe()

        if (hasattr(df, "to_pandas")):
            df = to_host(df)

        # A cumulative, order-derived feature in the style of IncrementColumn: each row's ordinal among its
        # entity's rows within the emitted window. Canonicalization erases row *order*, so without a *value*
        # that depends on order, the permutation check could never fail and would prove nothing. This column is
        # what gives that check teeth: remove the stage's sort and permuted input changes these values.
        df["window_seq"] = df.groupby("src_ip").cumcount()

        frames.append(df)

    combined = pd.concat(frames, ignore_index=True)

    return canonicalize(combined, key_columns=KEY_COLUMNS, ignore_columns=IGNORE_COLUMNS)
